name: Build

on:
  workflow_call:
    inputs:
      command:
        required: true
        description: Commands to run as JSON array
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nix
        uses: ./nix-setup
        with:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: ${{ inputs.command }}
