name: Nix Setup
inputs:
  CACHIX_AUTH_TOKEN:
    required: false
runs:
  using: "composite"
  steps:
    # Takes about 4 seconds
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          keep-env-derivations = true
          keep-outputs = true

    # This will take most of the step time
    # Reuses downloaded packages from previous CI runs
    - name: Restore and save Nix store
      uses: nix-community/cache-nix-action@v7
      with:
        # restore and save a cache using this key (per job)
        primary-key: nix-${{ runner.os }}-${{ github.job }}
        # if there's no cache hit, restore a cache by this prefix
        restore-prefixes-first-match: nix-${{ runner.os }}
        # collect garbage until the Nix store size (in bytes) is at most this number
        # before trying to save a new cache
        gc-max-store-size-linux: 5G

    # Optionally pushes to cachix if the token is present
    - uses: cachix/cachix-action@v17
      with:
        name: hyprland
        authToken: ${{ inputs.CACHIX_AUTH_TOKEN }}
